# CI/CD to run tests on commit
on:
 push:
  branches:
   - main
   - dev
  paths-ignore: '**.md'
 pull_request:
  branches:
   - main
   - dev
  paths-ignore: '**.md'

name: unit-tests

jobs:
 unit-tests:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Setup node
    uses:  actions/setup-node@v2
    with:
     node-version: 12.x
   - run: npm ci
   - npm: test
